### ISSUE TITLE
[URGENT] Broken input styling in FF

### ISSUE THREAD

**Issue by petrsloup** [klokantech/styles#5]
Originally reported at https://github.com/klokantech/osmnames-sphinxsearch/issues/34, but the inputs are broken in FF everywhere we use these styles (even on http://klokantech.github.io/styles/):

![image](https://cloud.githubusercontent.com/assets/707817/18384677/37f51d20-768c-11e6-837d-5550a25e6dfc.png)

**But also in other projects**:
OSMNames:

![image](https://cloud.githubusercontent.com/assets/707817/18384684/420d82ca-768c-11e6-90a4-3c32ebc1c846.png)

GR4:
![image](https://cloud.githubusercontent.com/assets/707817/18384686/4634334e-768c-11e6-84bf-00b3b1d980fe.png)

Maptiler.com:
![image](https://cloud.githubusercontent.com/assets/707817/18384712/6d17bf08-768c-11e6-8ab3-3097f7c6790e.png)

Happens in FF 47.0.1, 48.0, not sure about other versions.

**Comment by daliborjanak** [comment]
We need to finish form styling. This is fixed
