### ISSUE TITLE
"Share on" widget

### ISSUE THREAD

**Issue by klokan** [klokantech/styles#6]
"Share on" section similar to the one on OldMapsOnline.org, but with bigger icons for the social networks - and maybe a prefilled quote above for more prominent tweeting.

![screenshot 2016-10-08 at 17 48 58](https://cloud.githubusercontent.com/assets/59284/19214287/85404186-8d7f-11e6-8101-2828fb7d93ef.png)

We could have also a variant with "Click to Tweet" for blog or websites.
http://www.blogtyrant.com/click-to-tweet-this-quote-blog-posts/

![screenshot 2016-10-08 at 17 36 47](https://cloud.githubusercontent.com/assets/59284/19214295/b0810042-8d7f-11e6-8b7a-bb1b812fb258.png)

Or a block with a Quote like down on https://www.mapbox.com/blog/mapbox-studio-building-heights/?

![screenshot 2016-10-08 at 17 41 07](https://cloud.githubusercontent.com/assets/59284/19214296/b482c4aa-8d7f-11e6-91fd-07bb647bf77f.png)

@klokantech could use always the same look & feel for such a widget on all projects.

It should be applied on MapTiler pages (How-to and other), KlokanTech blog posts, etc.

Related to https://github.com/OSMNames/www.osmnames.org/issues/2

**Comment by daliborjanak** [comment]
http://klokantech.github.io/styles/components/

**Comment by daliborjanak** [comment]
Buttons variation created and used in our products. Documented in http://www.maptiler.com/maptilerlayer/ We don't need quotes now. We can do it if some project will need it.

**Comment by vaclavjanak** [comment]
Social buttons are updated and implemented.
